### ISSUE TITLE
what happens when a table is too wide @Melkiades

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/table.drawing.research#4]
does `gt_save(pdf)` work for large tables? otherwise rmarkdown works? (does it do pagination?)

**Comment by ayogasekaram** [comment]
quarto rendered pdf does some weird wrapping, with overlapping text.

<img width="322" alt="image" src="https://github.com/user-attachments/assets/b04f8872-5d8b-4ee7-90ea-144691e67b6a">

**Comment by Melkiades** [comment]
> quarto rendered pdf does some weird wrapping, with overlapping text.
> 
> <img alt="image" width="322" src="https://private-user-images.githubusercontent.com/73252787/375405353-b04f8872-5d8b-4ee7-90ea-144691e67b6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NzIxMzgsIm5iZiI6MTcyOTY3MTgzOCwicGF0aCI6Ii83MzI1Mjc4Ny8zNzU0MDUzNTMtYjA0Zjg4NzItNWQ4Yi00ZWU3LTkwZWEtMTQ0NjkxZTY3YjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA4MjM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYzhjOTA0M2E2MmRmNGNmMjdjYTQ4ZTI1MmE4MmViZTlkODE3OTU4NzcyZTM1NzBlOWE0NzhlYTAxNzBhNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DtC9EZkBL3RZxQUzFwyef0THk5oydCepgx6-PGLj18g">

argh that is not great

**Comment by ayogasekaram** [comment]
completed in https://github.com/insightsengineering/table.drawing.research/pull/8
